include:
  - project: "marburg/gitlab-ci-templates"
    file: "/linting-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/build-docker-image-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/gradle-test-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/gradle-integration-test-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/semantic-release-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "npm-setup-template.yml"

tests and report:
  extends: unit tests
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/jacoco/coverage.csv

stages:
  - lint
  - build
  - test
  - release
