include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: "marburg/gitlab-ci-templates"
    file: "/linting-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/build-docker-image-template.yml"
  # - project: "marburg/gitlab-ci-templates"
  #   file: "/gradle-test-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/gradle-integration-test-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "/semantic-release-template.yml"
  - project: "marburg/gitlab-ci-templates"
    file: "npm-setup-template.yml"

unit tests:
  image: adoptopenjdk/openjdk11:alpine-slim
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/jacoco/coverage.csv
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

stages:
  - lint
  - build
  - test
  - release
