spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/lab-to-fhir/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${SSL_KEY_STORE_LOCATION_INTERNAL:/opt/lab-to-fhir/ssl/keystore.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}

  cloud:
    function:
      definition: aim;hl7
    stream:
      bindings:
        # aim source
        aim-in-0:
          destination: ${AIM_TOPIC:aim-lab}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY:3}
        aim-out-0:
          destination: ${OUTPUT_TOPIC:lab-fhir-idat}
        # hl7 source
        hl7-in-0:
          destination: ${HL7_TOPIC:hl7-lab}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY:3}
        hl7-out-0:
          destination: ${OUTPUT_TOPIC:lab-fhir-idat}
      kafka:
        streams:
          binder:
            functions:
              aim:
                applicationId: aim-lab-to-fhir
              hl7:
                applicationId: hl7-lab-to-fhir
            configuration:
              compression.type: gzip
              max.request.size: 5242880
              spring.json.use.type.headers: "false"
            replicationFactor: ${REPLICATION_FACTOR:3}
            minPartitionCount: ${MIN_PARTITION_COUNT:3}

fhir:
  systems:
    serviceRequestId: "https://fhir.diz.uni-marburg.de/sid/lab-service-request-id"
    diagnosticReportId: "https://fhir.diz.uni-marburg.de/sid/lab-report-id"
    observationId: "https://fhir.diz.uni-marburg.de/sid/lab-surrogate-observation-id"
    patientId: "https://fhir.diz.uni-marburg.de/sid/patient-id"
    encounterId: "https://fhir.diz.uni-marburg.de/sid/encounter-admit-id"
    assignerId: "https://www.medizininformatik-initiative.de/fhir/core/NamingSystem/org-identifier"
    assignerCode: "UKMR"
    laboratorySystem: "https://fhir.diz.uni-marburg.de/CodeSystem/swisslab-code"
    laboratoryUnitSystem: "https://fhir.diz.uni-marburg.de/CodeSystem/swisslab-unit"
    mapperTagSystem: "https://fhir.diz.uni-marburg.de/CodeSystem/mapper"

mapping:
  aim:
    enabled: true
    filter: # e.g. "<2024-01-01"
  hl7:
    enabled: true
    filter: # e.g. ">=2024-01-01"

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.labtofhir: ${LOG_LEVEL:info}
