services:

  lab-to-fhir:
    image: ghcr.io/diz-unimr/lab-to-fhir:latest
    environment:
      AIM_TOPIC: aim-lab
      HL7_TOPIC: hl7-lab
      OUTPUT_TOPIC: lab-test
      LOG_LEVEL: info
      MAPPING_AIM_FILTER: "<2022-01-01"
      MAPPING_HL7_FILTER: ">=2022-01-01"
      CONSUMER_CONCURRENCY: 3
      REPLICATION_FACTOR: 3
      MIN_PARTITION_COUNT: 3
    ports:
      - "${LAB_WEB_PORT}:8080"
    volumes:
      - ${LAB_SSL_KEY_STORE_LOCATION}:/opt/lab-to-fhir/ssl/keystore.jks
      - ${LAB_SSL_TRUST_STORE_LOCATION}:/opt/lab-to-fhir/ssl/truststore.jks
