version: "3.7"

services:
  lab-to-fhir:
    image: registry.diz.uni-marburg.de/etl/lab-to-fhir:${IMAGE_TAG:-latest}
    environment:
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS_IN_0_DESTINATION: ${INPUT_TOPIC:-aim-lab}
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS_OUT_0_DESTINATION: ${OUTPUT_TOPIC:-lab-fhir}
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS_OUT_0_ERROR: ${ERROR_TOPIC:-lab-fhir-error}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: ${KAFKA_BROKERS}
      SERVICES_PSEUDONYMIZER_URL: ${PSEUDONYMIZER_URL}
      SECURITY_PROTOCOL: SSL
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SSL_TRUST_STORE_PASSWORD: ${SSL_TRUST_STORE_PASSWORD}
      MAPPING_LOINC_VERSION: ${LOINC_PACKAGE_VERSION}
      MAPPING_LOINC_CREDENTIALS_USER: ${PACKAGE_REGISTRY_USER}
      MAPPING_LOINC_CREDENTIALS_PASSWORD: ${PACKAGE_REGISTRY_PASSWORD}
    ports:
      - "${WEB_PORT:-8090}:8080"
    volumes:
      - ${SSL_KEYSTORE_LOCATION}:/opt/lab-to-fhir/ssl/keystore.jks
      - ${SSL_TRUSTSTORE_LOCATION}:/opt/lab-to-fhir/ssl/truststore.jks
